WIP: Strikes range screen
op-energy-foundation/op-energy-blockspan-service pull request #41
Opened 2024-06-24 06:39 UTC by Natsvora

2024-07-10 10:30 UTC, dambaev requested changes

2024-07-11 12:03 UTC, Natsvora commented on frontend/src/app/oe/interceptors/auth.interceptor.ts
> +    if (request.url.includes('blocktime/past/strike')) {
Now we don't need it as we have moved token to auth header fixed

2024-07-11 12:17 UTC, Natsvora commented on frontend/src/app/oe/services/oe-energy.service.ts
> +  $pastStrikesWithFilter(
done

2024-07-12 03:12 UTC, dambaev approved these changes

2024-07-15 08:28 UTC, merged