Added suggested changes for blockspan details screen
op-energy-foundation/op-energy-blockspan-service pull request #76
Opened 2024-12-12 17:10 UTC by Natsvora

Added suggested changes for blockspan details screen

2024-12-18 03:29 UTC, dambaev requested changes

2024-12-20 06:17 UTC, Natsvora commented on frontend/src/app/oe/utils/helper.ts
> +  const strikeTime = mediantime + 2016 * 600;
Done

2024-12-20 06:18 UTC, Natsvora commented on frontend/src/app/oe/utils/helper.ts
> +  const nextEpochEndBlock = nextEpochStartBlock + 2016;
end block is 'epochStartBlock + 2016' not 2015 If we use 2015 then span difference is 2015 we need span difference 2016

2024-12-20 06:18 UTC, Natsvora commented on frontend/src/app/oe/utils/helper.ts
> +  const nextEpochStartBlock = currentEpochIdx * 2016;
Corrected

2025-01-16 03:02 UTC, dambaev approved these changes
looks ok to me

2025-01-16 03:20 UTC, merged